name: Daily Accuracy Benchmark

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 2:00 AM, Beijing time.
    - cron: '0 18 * * *' # This is UTC time

jobs:
  accuracy_benchmark:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Perform the accuracy benchmark
      run: |
        docker pull $UT_IMAGE
        echo 'Running accuracy benchmark...'
        docker run \
          -v $PWD:$PWD \
          -w $PWD \
          --net host \
          --ipc host \
          --shm-size 80G \
          -t --rm \
          --gpus all \
          $UT_IMAGE bash -c ' \
            git config --global --add safe.directory $PWD && \
            pip install -e . && \
            cd benchmarks/accuracy && NPROC_PER_NODE=4 bash ./run.sh'
      env:
        UT_IMAGE: ${{ secrets.UT_IMAGE }}
