name: Daily Image Building Script Execution

on: 
  pull_request:
  push:
    branches:
      - master
    tags:
      - r[0-9]+.[0-9]+


jobs:
  run-shell-script:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run unit test
      run: |
        docker pull $UT_IMAGE
        docker run -v $PWD:$PWD -w $PWD --net host --ipc host --shm-size 80G  -it --rm --gpus all $UT_IMAGE bash -c 'pip install -r requirements/requirements-test.txt && bash tests/run_ut.sh'
      env: 
        UT_IMAGE: ${{ secrets.UT_IMAGE }}
